'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class MITRADBDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=MITRADBDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Customers() As DbSet(Of Customer)

    Public Overridable Function Validate_User(pUsername As String, pFirstName As String, pLastName As String, pPassword As String, pSecurityQuestion As String, pSecurityAnswer As String) As ObjectResult(Of String)
        Dim pUsernameParameter As ObjectParameter = If(pUsername IsNot Nothing, New ObjectParameter("pUsername", pUsername), New ObjectParameter("pUsername", GetType(String)))

        Dim pFirstNameParameter As ObjectParameter = If(pFirstName IsNot Nothing, New ObjectParameter("pFirstName", pFirstName), New ObjectParameter("pFirstName", GetType(String)))

        Dim pLastNameParameter As ObjectParameter = If(pLastName IsNot Nothing, New ObjectParameter("pLastName", pLastName), New ObjectParameter("pLastName", GetType(String)))

        Dim pPasswordParameter As ObjectParameter = If(pPassword IsNot Nothing, New ObjectParameter("pPassword", pPassword), New ObjectParameter("pPassword", GetType(String)))

        Dim pSecurityQuestionParameter As ObjectParameter = If(pSecurityQuestion IsNot Nothing, New ObjectParameter("pSecurityQuestion", pSecurityQuestion), New ObjectParameter("pSecurityQuestion", GetType(String)))

        Dim pSecurityAnswerParameter As ObjectParameter = If(pSecurityAnswer IsNot Nothing, New ObjectParameter("pSecurityAnswer", pSecurityAnswer), New ObjectParameter("pSecurityAnswer", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("Validate_User", pUsernameParameter, pFirstNameParameter, pLastNameParameter, pPasswordParameter, pSecurityQuestionParameter, pSecurityAnswerParameter)
    End Function

    Public Overridable Function Validate_UserName(username As String) As ObjectResult(Of String)
        Dim usernameParameter As ObjectParameter = If(username IsNot Nothing, New ObjectParameter("Username", username), New ObjectParameter("Username", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("Validate_UserName", usernameParameter)
    End Function

End Class
