-- CREATE Customer TABLE
PRINT 'CREATING SecurityQuestion TABLE...'
CREATE TABLE SecurityQuestion(
QuestionId INTEGER NOT NULL,
Question NVARCHAR(50)  NOT NULL,
CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP 
PRIMARY KEY (QuestionId));
GO

-- CREATE Customers TABLE
PRINT 'CREATING CUSTOMERS TABLE...'
CREATE TABLE Customers(
Username NVARCHAR(30) NOT NULL,
Firstname NVARCHAR(50)  NOT NULL, 
Lastname NVARCHAR(50) NOT NULL,
PasswordHash BINARY(64) NOT NULL,
Salt UNIQUEIDENTIFIER ,
CustomerStatus BIT NOT NULL,
CreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(QuestionId) REFERENCES SecurityQuestion(QuestionId),
CONSTRAINT [PK_Customer_Username] PRIMARY KEY  (Username));
GO


-- CREATE USERS QA TABLE
PRINT 'CREATING CustomersSecurityQuestion TABLE...'
CREATE TABLE CustomersSecurity(
Username NVARCHAR(30) NOT NULL,
QuestionId INTEGER NOT NULL,
Answer VARCHAR(50) NOT NULL,
CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (Username, QuestionId),
FOREIGN KEY (Username) REFERENCES Customers(Username), 
FOREIGN KEY(QuestionId) REFERENCES SecurityQuestion(QuestionId));
GO
